intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{tts}: include/{hxx ixx txx}{**}  $intf_libs

# Build options.
#
cxx.poptions =+ "-I$src_base/include"

# Export options.
#
lib{tts}:
{
  cxx.export.poptions = "-I$src_base/include"
  cxx.export.libs = $intf_libs
}

# Install into the libtts/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
include/
{
  {hxx ixx txx}{*}:
  {
    install         = include/
    install.subdirs = true
  }
}

